# @package _global_

defaults:
  - /tasks: obj_nav_hssd
  - /habitat_baselines: habitat_baselines_rl_config_base
  - /habitat/simulator/sim_sensors@habitat_baselines.eval.extra_sim_sensors.third_rgb_sensor: third_rgb_sensor
  - _self_

habitat:
  dataset:
    type: "RearrangeDatasetTransformers-v0"
  env_task: "CustomGymHabitatEnv"
  task:
    measurements:
      force_terminate:
        max_accum_force: -1
        max_instant_force: -1
      custom_predicate_task_success:
        must_call_stop: False
        must_see_object: True
        max_angle: 60
      custom_predicate_task_reward:
        dist_reward: 1.0
        angle_dist_reward: 1.0
        should_reward_turn: True
        constraint_violate_pen: 0.0
        force_pen: 0.0
        max_force_pen: 0.0
        force_end_pen: 0.0
        bad_term_pen: 0.0
        end_on_bad_termination: False
    fix_position_same_episode: False
    fix_target_same_episode: False
    target_type: object_type
    target_sampling_strategy: object_type
  environment:
    max_episode_steps: 1024
  simulator:
    habitat_sim_v0:
      allow_sliding: True

habitat_baselines:
  evaluator:
    _target_: memo.trainer.TransformersRepEpsHabitatEvaluator
  verbose: False
  trainer_name: "transformers"
  torch_gpu_id: 0
  tensorboard_dir: "tb"
  video_dir: "video_dir"
  video_fps: 30
  test_episode_count: -1
  eval_ckpt_path_dir: "data/new_checkpoints"
  num_environments: 24
  writer_type: 'tb'
  checkpoint_folder: "data/new_checkpoints"
  num_updates: -1
  total_num_steps: 1.0e8
  log_interval: 10
  num_checkpoints: 20
  reset_envs_after_update: True
  call_after_update_env: True
  # Force PyTorch to be single threaded as
  # this improves performance considerably
  force_torch_single_threaded: True
  eval_keys_to_include_in_name: ['reward', 'force', 'success']
  rollout_storage_name: MinimalTransformerRolloutStorage
  updater_name: "MinimalTransformerPPO"
  distrib_updater_name: "DistributedMinimalTransformerPPO"

  eval:
    video_option: ["disk"]

  rl:
    agent:
      type: TransformerSingleAgentAccessMgr

    policy:
      main_agent:
        name: PointNavResNetTransformerPolicy
        action_distribution_type: gaussian
        action_dist:
          use_log_std: True
          use_std_param: True
          std_init: -1
        transformer_config:
          model_name: "llamarl"
          n_layers: 4
          n_heads: 8
          n_hidden: 256
          n_mlp_hidden: 1024
          kv_size: 32
          activation: "gelu_new"
          inter_episodes_attention: True
          reset_position_index: False
          add_sequence_idx_embed: False
          position_embed_type: rope
          gated_residual: False
          context_len: 0
          banded_attention: False
          orphan_steps_attention: True
          add_context_loss: False
          depth_dropout_p: 0.1
        vc1_config:
          is_2d_output: True
          avg_pool_size: 2
        training_precision_config:
          visual_encoder: float16

    ppo:
      # ppo params
      clip_param: 0.2
      ppo_epoch: 2
      num_mini_batch: 3
      grad_accum_mini_batches: 1
      value_loss_coef: 0.5
      entropy_coef: 0.001
      lr: 2e-4
      warmup: False
      warmup_total_iters: 15000
      warmup_start_factor: 1e-3
      lr_scheduler: ""
      eps: 1e-5
      max_grad_norm: 0.2
      num_steps: 1280
      use_gae: True
      gamma: 0.99
      tau: 0.95
      use_linear_clip_decay: False
      use_linear_lr_decay: False
      reward_window_size: 50

      use_normalized_advantage: True

      hidden_size: 512

      # Use double buffered sampling, typically helps
      # when environment time is similar or larger than
      # policy inference time during rollout generation
      use_double_buffered_sampler: False
      update_stale_kv: True
      update_stale_values: False
      full_updates_per_rollout: 1
      updates_per_rollout: 1
      ignore_old_obs_grad: False
      storage_low_precision: True

    ddppo:
      sync_frac: 0.6
      # The PyTorch distributed backend to use
      distrib_backend: NCCL
      # Visual encoder backbone
      pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
      # Initialize with pretrained weights
      pretrained: False
      # Initialize just the visual encoder backbone with pretrained weights
      pretrained_encoder: False
      # Whether the visual encoder backbone will be trained.
      train_encoder: False
      # Whether to reset the critic linear layer
      reset_critic: True

      # Model parameters
      backbone: vc1_vc1_vitb_comp
      rnn_type: transformer
      num_recurrent_layers: 2
